### ISSUE TITLE
Updated documentation covering TLS-450

### ISSUE THREAD

**Issue by GrantBlack** [eredden/Veeder-Root-TLS-Socket-Library#1]
Noticed the version of the reference manual you are using is quite old, so will attached a much newer version 

The old commands (like I20100 for inventory) work unchanged, but some commands have been added or deprecated over time.
I have tested the commands with VR TLS-450 & TLS4 ATGs, but also found that other third party ATGs like Pro-gauge and Franklin also support a subset of the VR serial commands.

Am testing your library now with ATG I have on the bench to confirm everything works.

[577013-950T - Serial Protocol Interface.pdf](https://github.com/eredden/Veeder-Root-TLS-Socket-Library/files/14926846/577013-950T.-.Serial.Protocol.Interface.pdf)

**Comment by eredden** [comment]
Hello Grant!

Most of my testing for this library was on the TLS-3xx systems as I happened to have access to one for testing. While the protocol used for both 3xx and 4xx systems appears to be the same, the functions certainly are different! I'll update the documentation to link to the newer serial protocol interface and reference the older one as well.

Feel free to shoot over another issue if you happen to run into any bugs with the library while doing your bench testing! I will close this out once the documentation has been updated.

**Comment by eredden** [comment]
I have updated the referenced manual to be for the TLS-4xx systems -- I assume that [this manual](https://accuflo.com/pdf/veeder/577013-950.pdf) from Accuflo was the one you attached to this issue, so I have used that as the link instead of the original one I had in there.

Let me know if this looks good!

**Comment by GrantBlack** [comment]
> I have updated the referenced manual to be for the TLS-4xx systems -- I assume that [this manual](https://accuflo.com/pdf/veeder/577013-950.pdf) from Accuflo was the one you attached to this issue, so I have used that as the link instead of the original one I had in there.
> 
> Let me know if this looks good!

577013 is the correct Veeder Root manual.
The one you linked to is version 'L' - which is still good. I mainly use 577013-950**M** but have a copy of 577013-950**T**

Gilbarco/Veeder-Root are normally pretty good at sharing documentation and updates (though I have found some useful undocumented calls), but can't seem to find a direct link to the manual online.

**Comment by eredden** [comment]
I was not aware the two documents were of different revisions! What I did is create a `docs` directory and added the serial manual PDF file you provided in there, then referenced the new placement of that manual in the `README.md` file.

Let me know if all looks good now!
